config/routes.rb
Rails.application.routes.draw do
  root :to => 'buses#index'
  
 resources :buses do
   resources :posts
 end
end

app/models/bus.rb
class Bus < ActiveRecord::Base
  has_many :posts
  validates :name,
  :presence => {:message => "This can't be blank."}
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :bus

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/buses_controller.rb
class BusesController < ApplicationController
  def index
    @buses = Bus.all
  end

  def show
    @bus = Bus.find(params[:id])
  end

  def new
    @bus = Bus.new
  end

  def create
    @bus = Bus.new(bus_params)
    if @bus.save
      flash[:notice] = "Success!"
      redirect_to buses_path
    else
      render :new
  end
end

  def edit
    @bus = Bus.find(params[:id])
  end

  def update
    @bus = Bus.find(params[:id])
    if @bus.update(bus_params)
      redirect_to bus_path
    else
      render :edit
    end
   end

   def destroy
     @bus = Bus.find(params[:id])
     @bus.destroy
     redirect_to buses_path
   end

  private
    def bus_params
      params.require(:bus).permit(:name, :type, :image)
    end

  end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @bus = Bus.find(params[:bus_id])
    @post = @bus.posts.new
  end

  def create
    @bus = Bus.find(params[:bus_id])
    @post = @bus.posts.new(post_params)
    if @post.save
      redirect_to bus_path(@post.bus)
    else
      render :new
    end
  end

  def destroy
    @bus = Bus.find(params[:bus_id])
    @post = @bus.posts.find(params[:id])
    @post.destroy
    redirect_to bus_path(@bus)
  end

  private
  def post_params
    params.require(:post).permit(:text, :name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/buses/_form.html.erb
<%= render "layouts/errors", :object => @bus %>

<!-- <%= form_for @bus do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :image %>
  <%= f.text_field :image %>
  <%= f.submit  %>
<% end %> -->

<%= simple_form_for @bus do |f| %>
  <%= f.input :name %>
  <%= f.input :image %>
  <%= f.button :submit %>
<% end %>

app/views/buses/edit.html.erb
<h1>Edit Bus</h1>

<div class="row">
  <div class="col-md-2 col-md-offset-5">
    <%= render "form" %>
  </div>
</div>

app/views/buses/index.html.erb
<center>
  <h2>{ categories }</h2>
  <div class="row">
    <% @buses.each do |bus| %>
    <div class="col-md-6">
      <h2><%= bus.name %><br></h2>
      <h3>
        <%= link_to bus_path(bus) do %>
        <%= image_tag("#{bus.image}") %>
        <%end%>
      </h3>
    </div>
    <% end %>
  </div>
</center>

<hr>

<center>
  <div class="click">
    <%= link_to new_bus_path do %>
    <% end %>
  </div>
  <h2><%= link_to "Add Bus", new_bus_path %></h2>
</center>

app/views/buses/new.html.erb
<h2>Got a New Type of Bus?</h2>
<h3>give it a category</h3>

<br>
<div class="row">
  <div class="col-md-2 col-md-offset-5">
    <%= render "form" %>
  </div>
</div>

app/views/buses/show.html.erb
<% content_for(:title, "Buses") %>

<%= link_to "Home", buses_path %> |
<%= link_to "Edit", edit_bus_path(@bus) %> |
<%= link_to "Delete", bus_path(@bus),
   {:method => "delete"} %>

<center>
<h1><%= @bus.name %></h1>
<%= image_tag("#{@bus.image}") %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
  <% if @bus.posts.any? %>
  <h4>{ Posts }</h4>


  <% @bus.posts.each do |post| %>

    <h4><%= post.name %></h4>
    <p><%= post.text %></p>
    <%= link_to "{ delete this post ^ }", bus_post_path(@bus, post),
      {:method => "delete"} %>
    <% end %>


    <% else %>
    <p>There are no posts yet!</p>
    <% end %>
    <h4><%= link_to "Add a post", new_bus_post_path(@bus) %></h4>
  </div>
</div>
</center>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
<h3>Please fix these errors:</h3>
<ul>
  <% object.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>
</ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link href='https://fonts.googleapis.com/css?family=Sintony' rel='stylesheet' type='text/css'>
  <title>BlissBus</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <title><%= yield(:title) %></title>
</head>
<div class='container'>
<body>
  <nav>
    <h1>Bliss Bus { Blog } </h1>
    <h3>tiny living on wheels</h3>

  <center>
     <%= link_to root_path do %>
     <%= image_tag("bus.png") %>
     <% end %><br>
  </center>

      <%= yield(:nav) %>
    <hr>
  </div>
  </nav>
  <center>
    <%= flash[:alert] %>
    <%= flash[:notice] %>
    <%= yield %>
  </center>
</body>

</html>

app/views/posts/_form.html.erb
<%= render('layouts/errors', :object => @post) %>

<!-- <%= form_for [@bus, @post] do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :text %>
<%= f.text_area :text %>
<p><%= f.submit %></p>
<% end %> -->

<%= simple_form_for [@bus, @post] do |f| %>
  <%= f.input :name %>
  <%= f.text_area :text %>
  <%= f.button :submit %>
<% end %>

app/views/posts/new.html.erb
<h1>New post for <%= @bus.name %></h1>

<div class="row">
  <div class="col-md-2 col-md-offset-5">
    <%= render "form" %>
  </div>
</div>